### ISSUE TITLE
Option to generate breakpoints as Sass map

### ISSUE THREAD

**Issue by patrickcate** [jenslind/drupal-breakpoints-scss#1]
First off, I love this plugin. 

It would be cool if there was an option to output the breakpoints as a Sass map, rather than individual variables. Some Sass plugins like [include-media](http://include-media.com) use a `$breakpoints` Sass map to centrally manage breakpoints.

**Comment by extralooping** [comment]
that would be really much appreciated

edit: added a pull request [https://github.com/jenslind/drupal-breakpoints-scss/pull/2](url)

**Comment by jenslind** [comment]
Fixed in `1.2.0` see the [docs](https://github.com/jenslind/drupal-breakpoints-scss#usage)
